GET http://localhost:3000/categories

###
GET http://localhost:3000/categories/6f060b0b-3453-4141-a6d6-99d3f9df583f

###
POST http://localhost:3000/categories
Content-Type: application/json

{
  "title": "testing"
}

###
PUT http://localhost:3000/categories/6f060b0b-3453-4141-a6d6-99d3f9df583f
Content-Type: application/json

{
  "title": "oie",
  "description": "eita lele"
}
