GET http://localhost:3000/categories

###
GET http://localhost:3000/categories/673ace89-dd17-44c3-ab14-9fe105516380

###
POST http://localhost:3000/categories
Content-Type: application/json

{
  "title": "testing"
}

###
PUT http://localhost:3000/categories/673ace89-dd17-44c3-ab14-9fe105516380
Content-Type: application/json

{
  "title": "oie",
  "description": "eita lele"
}
